language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp-cli
script: 
  - gulp
  - nyc mocha -r jsdom-global/register dist/test/test_runner.js
  - nyc report --reporter=text-lcov | coveralls